### PR TITLE
Fix crash when service annotation with sliceOfMaps elements has invalid sourceValue

### LINKED ISSUE #967: panic on invalid `sourceValue`
### What is the environment (Minikube, Openshift)?
CodeReady Containers version: 1.26.0+31f06c09
OpenShift version: 4.7.8 (embedded in executable)

### What is the SBO version used?
v0.7.1

### What are the steps to reproduce this issue?
  1. add an annotation to `Service` with invalid  `sourceValue`
   
```
service.binding/java-maven_port: path={.spec.ports},elementType=sliceOfMaps,sourceKey=name,sourceValue=asdf
```
  2. create `ServiceBinding` between deployment and `Service` that has above annotation. 
 

### What is the expected behaviour?

`stats.condition` should have an error telling me that I have specified invalid `sourceValue`

### What is the actual behaviour?

operator throws panic

### Service Binding Operator Logs
```
E0520 16:39:21.734840       1 runtime.go:78] Observed a panic: &reflect.ValueError{Method:"reflect.Value.Interface", Kind:0x0} (reflect: call of reflect.Value.Interface on zero Value)
goroutine 346 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1538ee0, 0xc000573ed8)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1538ee0, 0xc000573ed8)
	/usr/lib/golang/src/runtime/panic.go:965 +0x1b9
reflect.valueInterface(0x0, 0x0, 0x0, 0xc000355c01, 0x9, 0x7f3f88777f18)
	/usr/lib/golang/src/reflect/value.go:1021 +0x1ad
reflect.Value.Interface(...)
	/usr/lib/golang/src/reflect/value.go:1016
github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/collect.collectItems(0xc0008c99a0, 0x15, 0x1906688, 0xc000a8ebd0, 0x18f4b40, 0xc00007b900, 0x14fa440, 0xc0009a3950, 0x98, 0x0, ...)
	/tmp/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/collect/impl.go:192 +0x44e
github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/collect.collectItems(0x0, 0x0, 0x1906688, 0xc000a8ebd0, 0x18f4b40, 0xc00007b900, 0x14fa440, 0xc0009a3930, 0x98, 0x1544c60, ...)
	/tmp/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/collect/impl.go:185 +0x7a5
github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/collect.BindingItems(0x1906688, 0xc000a8ebd0)
	/tmp/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/collect/impl.go:87 +0x390
github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline.HandlerFunc.Handle(0x17a9130, 0x1906688, 0xc000a8ebd0)
	/tmp/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/api.go:160 +0x3a
github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/builder.(*impl).Process(0xc0007f5710, 0xc0009ee1c0, 0xb, 0xc0004e3020, 0x2)
	/tmp/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/builder/pipeline.go:26 +0xd8
github.com/redhat-developer/service-binding-operator/controllers.(*ServiceBindingReconciler).Reconcile(0xc000518000, 0xc00048dc50, 0xa, 0xc00048dc34, 0xa, 0xc0009a31f0, 0xc000229170, 0xc0004feb48, 0xc0004feb40)
	/tmp/github.com/redhat-developer/service-binding-operator/controllers/servicebinding_controller.go:88 +0x5d8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00016d3b0, 0x159c2c0, 0xc00003bac0, 0x0)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:244 +0x2a9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00016d3b0, 0xc0003b9800)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:218 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(...)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000523d00)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000523d00, 0x18bda00, 0xc0009612c0, 0x1, 0xc000480000)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000523d00, 0x3b9aca00, 0x0, 0x1, 0xc000480000)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000523d00, 0x3b9aca00, 0xc000480000)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:179 +0x3d6
panic: reflect: call of reflect.Value.Interface on zero Value [recovered]
	panic: reflect: call of reflect.Value.Interface on zero Value

goroutine 346 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1538ee0, 0xc000573ed8)
	/usr/lib/golang/src/runtime/panic.go:965 +0x1b9
reflect.valueInterface(0x0, 0x0, 0x0, 0xc000355c01, 0x9, 0x7f3f88777f18)
	/usr/lib/golang/src/reflect/value.go:1021 +0x1ad
reflect.Value.Interface(...)
	/usr/lib/golang/src/reflect/value.go:1016
github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/collect.collectItems(0xc0008c99a0, 0x15, 0x1906688, 0xc000a8ebd0, 0x18f4b40, 0xc00007b900, 0x14fa440, 0xc0009a3950, 0x98, 0x0, ...)
	/tmp/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/collect/impl.go:192 +0x44e
github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/collect.collectItems(0x0, 0x0, 0x1906688, 0xc000a8ebd0, 0x18f4b40, 0xc00007b900, 0x14fa440, 0xc0009a3930, 0x98, 0x1544c60, ...)
	/tmp/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/collect/impl.go:185 +0x7a5
github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/collect.BindingItems(0x1906688, 0xc000a8ebd0)
	/tmp/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/collect/impl.go:87 +0x390
github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline.HandlerFunc.Handle(0x17a9130, 0x1906688, 0xc000a8ebd0)
	/tmp/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/api.go:160 +0x3a
github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/builder.(*impl).Process(0xc0007f5710, 0xc0009ee1c0, 0xb, 0xc0004e3020, 0x2)
	/tmp/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/builder/pipeline.go:26 +0xd8
github.com/redhat-developer/service-binding-operator/controllers.(*ServiceBindingReconciler).Reconcile(0xc000518000, 0xc00048dc50, 0xa, 0xc00048dc34, 0xa, 0xc0009a31f0, 0xc000229170, 0xc0004feb48, 0xc0004feb40)
	/tmp/github.com/redhat-developer/service-binding-operator/controllers/servicebinding_controller.go:88 +0x5d8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00016d3b0, 0x159c2c0, 0xc00003bac0, 0x0)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:244 +0x2a9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00016d3b0, 0xc0003b9800)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:218 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(...)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000523d00)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000523d00, 0x18bda00, 0xc0009612c0, 0x1, 0xc000480000)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000523d00, 0x3b9aca00, 0x0, 0x1, 0xc000480000)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000523d00, 0x3b9aca00, 0xc000480000)
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/tmp/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:179 +0x3d6
```

### PR DESCRIPTION
**Pull request by sadlerap**
### Motivation

When using the `sliceOfMaps` elementType in a service binding annotation, the operator panics when the specified sourceValue does not exist in the underlying maps, although the expected behavior would be to inform the user the binding has an error through conditions.

### Changes

This PR changes the current behavior by verifying that the extracted value is present, and reports an error in the service binding in the case that the sourceValue key isn't present.

Replaces #993 and fixes #967.

### Testing

See #967 for reproducibility details.

### CODE REVIEW

File: pkg/reconcile/pipeline/handler/collect/impl_test.go [hunk 1]
```diff
@@ -1030,6 +1030,71 @@ var _ = Describe("Integration Collect definitions + items", func() {
...
+
+	AfterEach(func() {
+		mockCtrl.Finish()
+	})
+
+	type testCase struct {
+		serviceContent map[string]interface{}
+	}
+
+	It("should set an error condition",
```
Comment (pedjak) [inline pkg/reconcile/pipeline/handler/collect/impl_test.go:1050]: this should be actually added around this line https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/reconcile/pipeline/handler/collect/impl_test.go#L390

The test name should describe the fixture and the expected outcome - "should set an error condition" does not say anything about under what condition and kind of error.

File: pkg/reconcile/pipeline/handler/collect/impl_test.go [hunk 2]
```diff
@@ -1030,6 +1030,71 @@ var _ = Describe("Integration Collect definitions + items", func() {
...
+		func() {
+			tc := testCase{
```
Comment (pedjak) [inline pkg/reconcile/pipeline/handler/collect/impl_test.go:1052]: is any particular reason why use a new struct here, instead of just defining `serviceContent` variable directly and using it throughout the test?

File: pkg/reconcile/pipeline/handler/collect/impl_test.go [hunk 3]
```diff
@@ -1030,6 +1030,71 @@ var _ = Describe("Integration Collect definitions + items", func() {
...
+						},
+					},
+				},
+			}
+
+			ctx := mocks.NewMockContext(mockCtrl)
+			service := mocks.NewMockService(mockCtrl)
+			serviceResource := &unstructured.Unstructured{Object: tc.serviceContent}
+
+			ctx.EXPECT().Services().Return([]pipeline.Service{service}, nil).MinTimes(1)
```
Comment (pedjak) [inline pkg/reconcile/pipeline/handler/collect/impl_test.go:1071]: `MinTimes(1)` is default if omitted, hence I would remove it.

File: pkg/reconcile/pipeline/handler/collect/impl_test.go [hunk 4]
```diff
@@ -1030,6 +1030,71 @@ var _ = Describe("Integration Collect definitions + items", func() {
...
+
+			ctx.EXPECT().SetCondition(
+				apis.Conditions().NotCollectionReady().
+					Reason(collect.ValueNotFound).
+					Msg("Value for key java-maven_port_foo not found").
+					Build())
+			ctx.EXPECT().Error(collect.ErrorValueNotFound)
+			ctx.EXPECT().StopProcessing()
+
+			collect.BindingDefinitions(ctx)
```
Comment (pedjak) [inline pkg/reconcile/pipeline/handler/collect/impl_test.go:1091]: this test should check the behavior of `BindingItems` stage only, we do not need perform an integration test here. Let's reduce the test to unit test by dropping this line and modifying the setup accordingly.

File: test/acceptance/features/bindAppToServiceAnnotations.feature [hunk 5]
```diff
@@ -542,3 +542,49 @@ Feature: Bind an application to a service using annotations
             """
         Then Service Binding "binding-app-via-gvk" is ready
         And The application env var "BACKEND_HOST_INTERNAL_DB" has value "internal.db.stable.example.com"
+
+    Scenario: Bind application to service with invalid sourceValue annotations
```
Comment (pedjak) [inline test/acceptance/features/bindAppToServiceAnnotations.feature:546]: the scenario description suggests that the binding is performed, but actually it is not. Hence, we should reflect that, e.g.

"Application cannot be bound to service containing annotation with an invalid sourceValue value"

File: test/acceptance/features/bindAppToServiceAnnotations.feature [hunk 6]
```diff
@@ -542,3 +542,49 @@ Feature: Bind an application to a service using annotations
...
+                    name: $scenario_id
+                application:
+                    name: $scenario_id
+                    group: apps
+                    version: v1
+                    resource: deployments
+            """
+        Then Service Binding CollectionReady.status is "False"
+	And Service Binding CollectionReady.reason is "ValueNotFound"
+	And Service Binding CollectionReady.message is "Value for key webarrows_primary not found"
```
Comment (pedjak) [inline test/acceptance/features/bindAppToServiceAnnotations.feature:589]: acceptance tests are failing on CI on this assertion, please double check what is going on.

**Review by pedjak — CHANGES_REQUESTED** [review]

File: test/acceptance/features/bindAppToServiceAnnotations.feature (hunk 6 above)
Comment (pmacik) [reply test/acceptance/features/bindAppToServiceAnnotations.feature:589]: I've looked into [the artifacts of the failing without-olm job](https://github.com/redhat-developer/service-binding-operator/suites/3715396067/artifacts/90835111) and found that this step is failing because the message is actually `Value for key webarrows_secondary not found`:
```shell
$ cat servicebindings.binding.operators.coreos.com.yaml| yq -r '.items[] | select(.metadata.name == "bindapptoserviceannotations-546").status.conditions[] | select(.type == "CollectionReady")'

{
  "lastTransitionTime": "2021-09-08T17:15:27Z",
  "message": "Value for key webarrows_secondary not found",
  "reason": "ValueNotFound",
  "status": "False",
  "type": "CollectionReady"
}
```

For comparison by checking the [artifacts of the passed with-olm job](https://github.com/redhat-developer/service-binding-operator/suites/3715396067/artifacts/90835110) the message is correct:
```shell
$ cat servicebindings.binding.operators.coreos.com.yaml| yq -r '.items[] | select(.metadata.name == "bindapptoserviceannotations-546").status.conditions[] | select(.type == "CollectionReady")'
{
  "lastTransitionTime": "2021-09-08T17:15:50Z",
  "message": "Value for key webarrows_primary not found",
  "reason": "ValueNotFound",
  "status": "False",
  "type": "CollectionReady"
}
```

Comment (pmacik) [reply test/acceptance/features/bindAppToServiceAnnotations.feature:589]: It looks like whatever is going through `.spec.connections` map keys do it in a different order for each of the above cases

File: pkg/reconcile/pipeline/handler/collect/impl_test.go (hunk 2 above)
Comment (sadlerap) [reply pkg/reconcile/pipeline/handler/collect/impl_test.go:1052]: Not particularly; there used to be more in this struct, but most of it got removed as a result of refactoring, leaving only this.  I'll take it out.

File: pkg/reconcile/pipeline/handler/collect/impl_test.go (hunk 3 above)
Comment (sadlerap) [reply pkg/reconcile/pipeline/handler/collect/impl_test.go:1071]: We need `MinTimes(1)` since we're asserting that we call `Services()` at least once, not exactly once.  Default behavior [appears to be](https://stackoverflow.com/questions/51206450/testing-with-gomock-returns-error-expected-call-has-already-been-called-the-max) asserting that it gets called exactly once.

File: test/acceptance/features/bindAppToServiceAnnotations.feature (hunk 5 above)
Comment (sadlerap) [reply test/acceptance/features/bindAppToServiceAnnotations.feature]: Fixed in 6054ca0c.

File: pkg/reconcile/pipeline/handler/collect/impl_test.go [hunk 7]
```diff
@@ -388,6 +388,62 @@ var _ = Describe("Collect Binding Data", func() {
...
+					definition := bindingmocks.NewMockDefinition(mockCtrl)
+					value := bindingmocks.NewMockValue(mockCtrl)
+
+					ctx.EXPECT().Services().Return([]pipeline.Service{service}, nil)
+
+					bindingDefs := []binding.Definition{definition}
+					service.EXPECT().BindingDefs().DoAndReturn(func() []binding.Definition { return bindingDefs })
+					service.EXPECT().Resource().Return(serviceResource)
+
+					definition.EXPECT().Apply(serviceResource).Return(value, nil)
```
Comment (pedjak) [inline pkg/reconcile/pipeline/handler/collect/impl_test.go:431]: given that we really mock this call, `serviceResource` value could be further simplified and reduce even to something like `unstructured.Unstructured{}`

File: pkg/reconcile/pipeline/handler/collect/impl_test.go [hunk 8]
```diff
@@ -388,6 +388,62 @@ var _ = Describe("Collect Binding Data", func() {
...
+					ctx := mocks.NewMockContext(mockCtrl)
+					service := mocks.NewMockService(mockCtrl)
+					serviceResource := &unstructured.Unstructured{Object: serviceContent}
+					definition := bindingmocks.NewMockDefinition(mockCtrl)
+					value := bindingmocks.NewMockValue(mockCtrl)
+
+					ctx.EXPECT().Services().Return([]pipeline.Service{service}, nil)
+
+					bindingDefs := []binding.Definition{definition}
+					service.EXPECT().BindingDefs().DoAndReturn(func() []binding.Definition { return bindingDefs })
```
Comment (pedjak) [inline pkg/reconcile/pipeline/handler/collect/impl_test.go:428]: these two lines could be collapsed in something like:

```
service.EXPECT().BindingDefs().Return(bindingDefs)
```

File: pkg/reconcile/pipeline/handler/collect/impl_test.go [hunk 9]
```diff
@@ -388,6 +388,62 @@ var _ = Describe("Collect Binding Data", func() {
...
+				mockCtrl *gomock.Controller
+			)
+
+			BeforeEach(func() {
+				mockCtrl = gomock.NewController(GinkgoT())
+			})
+
+			AfterEach(func() {
+				mockCtrl.Finish()
+			})
```
Comment (pedjak) [inline pkg/reconcile/pipeline/handler/collect/impl_test.go:402]: this is not needed because they are already declared in the outer context. With that, we can even remove introduced `Context`, because it does not contain any additional customizations.

File: pkg/reconcile/pipeline/handler/collect/impl_test.go [hunk 10]
```diff
@@ -388,6 +388,62 @@ var _ = Describe("Collect Binding Data", func() {
...
+
+			It("should set an error condition",
```
Comment (pedjak) [inline pkg/reconcile/pipeline/handler/collect/impl_test.go:404]: so, at the end, this test is not about the invalid `sourceValue` - it is certainly triggered by such annotation from user side, but here we have an unit test, and the trigger is `nil` value of collected binding. We should reflect that in the test name. Also, the outcome of this tests is not only to set the right error condition, we also indicate that processing should be stopped and not retried at all.

**Review by pedjak — APPROVED** [review]
looks good, apart from some comments on the introduced unit test. A few simplifications/test name improvements should be made to improve readability and maintainability. If this can be done quickly, I would suggest to do it then within this PR, otherwise, we should perform in the followup PR.

File: pkg/reconcile/pipeline/handler/collect/impl.go [hunk 11]
```diff
@@ -249,7 +252,17 @@ func collectItems(prefix string, ctx pipeline.Context, service pipeline.Service,
...
+			if mapVal := v.MapIndex(n).Interface(); mapVal != nil {
+				collectItems(p, ctx, service, n, mapVal)
+			} else {
+				condition := apis.Conditions().NotCollectionReady().
+					Msg(fmt.Sprintf("Value for key %v_%v not found", prefix+k.String(), n.String())).
+					Reason(ValueNotFound).Build()
+				ctx.SetCondition(condition)
+				ctx.Error(ErrorValueNotFound)
+				ctx.StopProcessing()
+				return
```
[the remark this answers is not in the document]
Comment (sadlerap) [reply pkg/reconcile/pipeline/handler/collect/impl.go:264]: Unless you think otherwise, I'll refactor this in a future PR.

[the remark this answers is not in the document]
Comment (pedjak) [reply pkg/reconcile/pipeline/handler/collect/impl.go:264]: ok
