### PR TITLE
e2e and other fixes

### LINKED ISSUE #244: End to End test fails with error `Intermediary secret contents are invalid`
```
    --- FAIL: TestAddSchemesToFramework/end-to-end (150.17s)
        --- FAIL: TestAddSchemesToFramework/end-to-end/scenario-db-app-sbr (30.09s)
            servicebindingrequest_test.go:190: Creating a new test context...
            servicebindingrequest_test.go:86: Initializing cluster resources...
            servicebindingrequest_test.go:96: Using namespace 'test-namespace-cfbb4589-bde1-46a4-b967-811d9c20e4b7' for testing...
            servicebindingrequest_test.go:119: Cleaning namespace:
            servicebindingrequest_test.go:121: 	Databases:
            servicebindingrequest_test.go:133: 	ServiceBindingRequests:
            servicebindingrequest_test.go:145: 	Deployments:
            servicebindingrequest_test.go:157: 	ClusterServiceVersions:
            servicebindingrequest_test.go:169: 	Secrets:
            servicebindingrequest_test.go:177: 		e2e-service-binding-request...
            servicebindingrequest_test.go:310: Starting end-to-end tests for operator!
            servicebindingrequest_test.go:312: Creating ClusterServiceVersion mock object...
            client.go:57: resource type ClusterServiceVersion with namespace/name (test-namespace-cfbb4589-bde1-46a4-b967-811d9c20e4b7/cluster-service-version) created
            servicebindingrequest_test.go:385: Creating Database mock object...
            client.go:57: resource type Database with namespace/name (test-namespace-cfbb4589-bde1-46a4-b967-811d9c20e4b7/e2e-db-testing) created
            servicebindingrequest_test.go:389: Updating Database status, adding 'DBCredentials'
            servicebindingrequest_test.go:394: Creating Database credentials secret mock object...
            client.go:57: resource type Secret with namespace/name (test-namespace-cfbb4589-bde1-46a4-b967-811d9c20e4b7/e2e-db-credentials) created
            servicebindingrequest_test.go:405: Creating Deployment mock object...
            client.go:57: resource type Deployment with namespace/name (test-namespace-cfbb4589-bde1-46a4-b967-811d9c20e4b7/e2e-application) created
            servicebindingrequest_test.go:410: Waiting for application deployment reach one replica...
            wait_util.go:64: Waiting for full availability of e2e-application deployment (0/1)
            wait_util.go:64: Waiting for full availability of e2e-application deployment (0/1)
            wait_util.go:64: Waiting for full availability of e2e-application deployment (0/1)
            wait_util.go:64: Waiting for full availability of e2e-application deployment (0/1)
            wait_util.go:70: Deployment available (1/1)
            servicebindingrequest_test.go:415: Reading application deployment 'e2e-application'
            servicebindingrequest_test.go:425: Creating ServiceBindingRequest mock object...
            client.go:57: resource type  with namespace/name (test-namespace-cfbb4589-bde1-46a4-b967-811d9c20e4b7/e2e-service-binding-request) created
            servicebindingrequest_test.go:337: Inspecting deployment structure...
            servicebindingrequest_test.go:339: Inspecting deployment 'test-namespace-cfbb4589-bde1-46a4-b967-811d9c20e4b7/e2e-application'
            servicebindingrequest_test.go:342: Error on inspecting deployment: '&errors.errorString{s:"can't find envFrom in first container"}'
            servicebindingrequest_test.go:339: Inspecting deployment 'test-namespace-cfbb4589-bde1-46a4-b967-811d9c20e4b7/e2e-application'
            servicebindingrequest_test.go:346: Deployment: Result after attempts, error: '<nil>'
            require.go:794: 
                	Error Trace:	servicebindingrequest_test.go:352
                	            				servicebindingrequest_test.go:197
                	            				servicebindingrequest_test.go:64
                	Error:      	Received unexpected error:
                	            	can't find DATABASE_SECRET_USER in data
                	Test:       	TestAddSchemesToFramework/end-to-end/scenario-db-app-sbr
                	Messages:   	Intermediary secret contents are invalid: nil
            client.go:75: resource type  with namespace/name (test-namespace-cfbb4589-bde1-46a4-b967-811d9c20e4b7/e2e-service-binding-request) successfully deleted
            client.go:75: resource type Deployment with namespace/name (test-namespace-cfbb4589-bde1-46a4-b967-811d9c20e4b7/e2e-application) successfully deleted
            client.go:75: resource type Secret with namespace/name (test-namespace-cfbb4589-bde1-46a4-b967-811d9c20e4b7/e2e-db-credentials) successfully deleted
            client.go:75: resource type Database with namespace/name (test-namespace-cfbb4589-bde1-46a4-b967-811d9c20e4b7/e2e-db-testing) successfully deleted
            client.go:75: resource type ClusterServiceVersion with namespace/name (test-namespace-cfbb4589-bde1-46a4-b967-811d9c20e4b7/cluster-service-version) successfully deleted
        --- FAIL: TestAddSchemesToFramework/end-to-end/scenario-sbr-db-app (120.08s)
```

### PR DESCRIPTION
**Pull request by isutton**
At the end, this PR ended longer than initially expected. Regardless of its
length, it attempts to make more explicit the usage of predicates for the
several watches that are initiated by the operator to avoid some situations that
could trigger an infinite loop in the reconciliation process.

This PR also continues and changes the approach taken to implement annotations
by creating a syntactic CRDDescription extracted from the manifest's
CRD's annotations. The relevant e2e test was transformed into a scenario in the
existing test infrastructure, after some changes such as transforming the
installation to a step.

Fixes #244

### CODE REVIEW

File: pkg/controller/servicebindingrequest/olm.go [hunk 1]
```diff
@@ -149,6 +164,103 @@ func (o *OLM) SelectCRDByGVK(gvk schema.GroupVersionKind) (*olmv1alpha1.CRDDescr
 	return crdDescriptions[0], nil
 }
 
+// buildCRDDescriptionFromCRDAnnotations builds a CRDDescription from annotations present in the CRD.
+func buildCRDDescriptionFromCRDAnnotations(crd *unstructured.Unstructured) (*unstructured.Unstructured, error) {
+	specDescriptors := []olmv1alpha1.SpecDescriptor{}
```
Comment (golangcibot) [inline pkg/controller/servicebindingrequest/olm.go]: ineffectual assignment to `specDescriptors` (from `ineffassign`)

File: pkg/controller/servicebindingrequest/olm.go [hunk 2]
```diff
@@ -149,6 +164,103 @@ func (o *OLM) SelectCRDByGVK(gvk schema.GroupVersionKind) (*olmv1alpha1.CRDDescr
...
+	statusDescriptors := []olmv1alpha1.StatusDescriptor{}
```
Comment (golangcibot) [inline pkg/controller/servicebindingrequest/olm.go]: ineffectual assignment to `statusDescriptors` (from `ineffassign`)

File: pkg/controller/servicebindingrequest/olm.go [hunk 3]
```diff
@@ -149,6 +164,103 @@ func (o *OLM) SelectCRDByGVK(gvk schema.GroupVersionKind) (*olmv1alpha1.CRDDescr
...
+
+	specDescriptors, statusDescriptors, err := buildDescriptorsFromAnnotations(crd.GetAnnotations())
```
Comment (golangcibot) [inline pkg/controller/servicebindingrequest/olm.go]: ineffectual assignment to `err` (from `ineffassign`)

**Comment by sbose78** [comment]
A green e2e 😳🥳

**Comment by sbose78** [comment]
Could you add a detailed description please?

File: test/e2e/servicebindingrequest_test.go [hunk 4]
```diff
@@ -63,26 +65,17 @@ func TestAddSchemesToFramework(t *testing.T) {
 		t.Run("scenario-db-app-sbr", func(t *testing.T) {
 			ServiceBindingRequest(t, []Step{DBStep, AppStep, SBRStep})
 		})
-
```
Comment (pmacik) [inline test/e2e/servicebindingrequest_test.go]: @isutton Why have you removed those scenarios? Those implements the e2e step permutations as described in https://jira.coreos.com/browse/APPSVC-126.

Is it intentional or accidental?

File: pkg/controller/servicebindingrequest/olm.go (hunk 1 above)
Comment (golangcibot) [inline pkg/controller/servicebindingrequest/olm.go]: ineffectual assignment to `specDescriptors` (from `ineffassign`)

File: pkg/controller/servicebindingrequest/olm.go (hunk 2 above)
Comment (golangcibot) [inline pkg/controller/servicebindingrequest/olm.go]: ineffectual assignment to `statusDescriptors` (from `ineffassign`)

**Comment by pmacik** [comment]
@isutton When I was on it, I unified the package used and error checking for all the testing, incl. the unit tests. https://github.com/isutton/service-binding-operator/pull/4

File: pkg/controller/servicebindingrequest/binder_test.go [hunk 5]
```diff
@@ -97,15 +95,19 @@ func TestBinderNew(t *testing.T) {
...
-		c := corev1.Container{}
-		u := containers[0].(map[string]interface{})
-		err = runtime.DefaultUnstructuredConverter.FromUnstructured(u, &c)
-		assert.NoError(t, err)
-		assert.NotEmpty(t, c.Env[0].Value)
-
-		parsedTime, err := time.Parse(time.RFC3339, c.Env[0].Value)
-		assert.NoError(t, err)
-		assert.True(t, parsedTime.Before(time.Now()))
+		// I believe the test subject here is the environment variable which was being populated by
```
Comment (sbose78) [inline pkg/controller/servicebindingrequest/binder_test.go]: .. so that when the secret content changes, we have a way to trigger a deployment.

Comment (isutton) [reply pkg/controller/servicebindingrequest/binder_test.go]: Reverted the comment and made it more clear why that environment variable is there.

File: pkg/controller/servicebindingrequest/annotations_test.go [hunk 6]
```diff
@@ -3,7 +3,7 @@ package servicebindingrequest
 import (
 	"testing"
 
-	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
```
Comment (baijum) [inline pkg/controller/servicebindingrequest/annotations_test.go]: I think we can use both assert and require. Use "require" for absolute required steps that are required for further assertions. See the below comment for an example.

File: pkg/controller/servicebindingrequest/binder_test.go [hunk 7]
```diff
@@ -55,60 +54,75 @@ func TestBinderNew(t *testing.T) {
...
 
 	t.Run("appendEnv", func(t *testing.T) {
 		d := mocks.DeploymentMock("binder", "binder", map[string]string{})
 		list := binder.appendEnvVar(d.Spec.Template.Spec.Containers[0].Env, "name", "value")
-		assert.Equal(t, 1, len(list))
-		assert.Equal(t, "name", list[0].Name)
-		assert.Equal(t, "value", list[0].Value)
+		require.Equal(t, 1, len(list))
+		require.Equal(t, "name", list[0].Name)
+		require.Equal(t, "value", list[0].Value)
```
Comment (baijum) [inline pkg/controller/servicebindingrequest/binder_test.go]: (See the previous comment) The length could be a `require` and the other two could be `assert`.

Comment (isutton) [reply pkg/controller/servicebindingrequest/binder_test.go]: This PR is already big enough, we should add an issue to evaluate our usage of `require` and `assert` in tests and deal with those as another work unit.

What do you think?

File: pkg/controller/servicebindingrequest/annotations_test.go (hunk 6 above)
Comment (isutton) [reply pkg/controller/servicebindingrequest/annotations_test.go]: I agree with this principle, let's continue on the other related comment.

File: pkg/controller/servicebindingrequest/binder_test.go (hunk 7 above)
Comment (baijum) [reply pkg/controller/servicebindingrequest/binder_test.go]: I am fine with that.

File: pkg/controller/servicebindingrequest/olm.go [hunk 8]
```diff
@@ -110,15 +112,27 @@ func (o *OLM) loopCRDDescriptions(
 }
 
 // SelectCRDByGVK return a single CRD based on a given GVK.
-func (o *OLM) SelectCRDByGVK(gvk schema.GroupVersionKind) (*olmv1alpha1.CRDDescription, error) {
+func (o *OLM) SelectCRDByGVK(gvk schema.GroupVersionKind, crd *unstructured.Unstructured) (*olmv1alpha1.CRDDescription, error) {
 	log := o.logger.WithValues("Selector.GVK", gvk)
```
Comment (otaviof) [inline pkg/controller/servicebindingrequest/olm.go]: @isutton would you use the name `logger` here?

File: pkg/controller/servicebindingrequest/olm.go [hunk 9]
```diff
@@ -142,13 +156,113 @@ func (o *OLM) SelectCRDByGVK(gvk schema.GroupVersionKind) (*olmv1alpha1.CRDDescr
...
+		Version:           version,
+		Kind:              kind,
+		SpecDescriptors:   specDescriptors,
+		StatusDescriptors: statusDescriptors,
+	}
+
+	return &crdDescription, nil
+}
+
+func buildDescriptorsFromAnnotations(annotations map[string]string) ([]olmv1alpha1.SpecDescriptor, []olmv1alpha1.StatusDescriptor, error) {
```
Comment (otaviof) [inline pkg/controller/servicebindingrequest/olm.go]: I'm missing the documentation comment on this method, and apparently, the amount of columns in this line is higher than 101 (defined by `.editorconfig`).

File: pkg/controller/servicebindingrequest/olm.go [hunk 10]
```diff
@@ -142,13 +156,113 @@ func (o *OLM) SelectCRDByGVK(gvk schema.GroupVersionKind) (*olmv1alpha1.CRDDescr
...
+			return nil, nil, err
+		}
+
+		collectedSpecDescriptors = append(collectedSpecDescriptors, mappedSpecDescriptors...)
+		collectedStatusDescriptors = append(collectedStatusDescriptors, mappedStatusDescriptors...)
+	}
+	return collectedSpecDescriptors, collectedStatusDescriptors, nil
+}
+
+const ServiceBindingOperatorAnnotationPrefix = "servicebindingoperator.redhat.io/"
```
Comment (otaviof) [inline pkg/controller/servicebindingrequest/olm.go]: We should move constant declarations to the top of the file.

File: pkg/controller/servicebindingrequest/reconciler.go [hunk 11]
```diff
@@ -239,8 +250,12 @@ func (r *Reconciler) Reconcile(request reconcile.Request) (reconcile.Result, err
 
 	// updating status of request instance
 	if err = r.updateStatusServiceBindingRequest(sbr, &sbrStatus); err != nil {
-		log.Error(err, "On updating status of ServiceBindingRequest.")
-		return RequeueError(err)
+		// requeue only in case of conflict
+		if k8serrors.IsConflict(err) {
```
Comment (otaviof) [inline pkg/controller/servicebindingrequest/reconciler.go]: @isutton `k8serrors` is not the alias used for that import throughout the code-base. Please use `errors` directly instead.

File: pkg/controller/servicebindingrequest/sbrcontroller.go [hunk 12]
```diff
@@ -84,29 +92,71 @@ func (s *SBRController) getWatchingGVKs() ([]schema.GroupVersionKind, error) {
...
+			return !e.DeleteStateUnknown
+		},
+	}
+}
+
 // AddWatchForGVK creates a watch on a given GVK, as long as it's not duplicated.
 func (s *SBRController) AddWatchForGVK(gvk schema.GroupVersionKind) error {
-	log := s.logger.WithValues("GVK", gvk)
-	log.Debug("Adding watch for GVK...")
+	l := s.logger.WithValues("GVK", gvk)
```
Comment (otaviof) [inline pkg/controller/servicebindingrequest/sbrcontroller.go]: @isutton also here, name it `logger` instead of `l`.

File: pkg/controller/servicebindingrequest/sbrcontroller_test.go [hunk 13]
```diff
@@ -0,0 +1,181 @@
...
+	corev1 "k8s.io/api/core/v1"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/runtime"
+	"sigs.k8s.io/controller-runtime/pkg/event"
+
+	"github.com/redhat-developer/service-binding-operator/pkg/apis/apps/v1alpha1"
+	"github.com/redhat-developer/service-binding-operator/pkg/log"
+)
+
+func Test_newSBRPredicate(t *testing.T) {
```
Comment (otaviof) [inline pkg/controller/servicebindingrequest/sbrcontroller_test.go]: @isutton please use the same standards for naming tests than the other methods, This would be named as `TestSBRControllerNewSBRPredicate` instead.

File: pkg/controller/servicebindingrequest/sbrcontroller_test.go [hunk 14]
```diff
@@ -0,0 +1,181 @@
...
+			t.Run(tt.name, func(t *testing.T) {
+				if got := pred.Delete(event.DeleteEvent{DeleteStateUnknown: tt.confirmDeleted}); got != tt.want {
+					t.Errorf("newSBRPredicate() = %v, want %v", got, tt.want)
+				}
+			})
+		}
+	})
+}
+
+func Test_newGVKPredicate(t *testing.T) {
```
Comment (otaviof) [inline pkg/controller/servicebindingrequest/sbrcontroller_test.go]: Same here.

File: pkg/controller/servicebindingrequest/olm.go (hunk 8 above)
Comment (isutton) [reply pkg/controller/servicebindingrequest/olm.go]: This PR isn't that small, so I prefer we add an issue to standardize this as a separate work unit. Is this fine?

File: pkg/controller/servicebindingrequest/reconciler.go (hunk 11 above)
Comment (isutton) [reply pkg/controller/servicebindingrequest/reconciler.go]: The `errors` package is already being exported and not aliased, and additionally the `k8serrors` package is an alias to `k8s.io/apimachinery/pkg/api/errors` which goal is to provide predicates for several Kubernetes specific errors.

File: pkg/controller/servicebindingrequest/olm.go (hunk 9 above)
Comment (isutton) [reply pkg/controller/servicebindingrequest/olm.go]: Solved in da312bdda4fcf1525cd9a40168d50247a4dde05e.

File: pkg/controller/servicebindingrequest/olm.go (hunk 10 above)
Comment (isutton) [reply pkg/controller/servicebindingrequest/olm.go]: Solved in 2c920273ac29e2e728b3adbc82ad737318de06ce.

File: pkg/controller/servicebindingrequest/sbrcontroller.go (hunk 12 above)
Comment (isutton) [reply pkg/controller/servicebindingrequest/sbrcontroller.go]: Solved in b3b8a636334c619945d6d816d1d3122c02312d2f.

File: pkg/controller/servicebindingrequest/sbrcontroller_test.go (hunk 13 above)
Comment (isutton) [reply pkg/controller/servicebindingrequest/sbrcontroller_test.go]: Solved in cc0d39e35f1f219cfd3f041d482c75186f870309.

File: pkg/controller/servicebindingrequest/sbrcontroller_test.go (hunk 14 above)
Comment (isutton) [reply pkg/controller/servicebindingrequest/sbrcontroller_test.go]: Solved in cc0d39e35f1f219cfd3f041d482c75186f870309.

File: pkg/controller/servicebindingrequest/reconciler.go (hunk 11 above)
Comment (otaviof) [reply pkg/controller/servicebindingrequest/reconciler.go]: Well, in that case, we should add an additional function in `common.go`, in order to handle this type of return, following what's being done for the other Reconciler return statements.

File: pkg/controller/servicebindingrequest/olm.go (hunk 8 above)
Comment (otaviof) [reply pkg/controller/servicebindingrequest/olm.go]: It's not about side, but about meaningful variable names. In this case, `logger` has been the one used everywhere, and we should use it here as well.

File: pkg/controller/servicebindingrequest/reconciler.go (hunk 11 above)
Comment (isutton) [reply pkg/controller/servicebindingrequest/reconciler.go]: Solved in 0a84edcfec0f1086902b4a68d458954f46ab3885.

**Comment by baijum** [comment]
Do we need the change in the Travis configuration file?

**Comment by otaviof** [comment]
> Do we need the change in the Travis configuration file?

Yes, it fixes problems we've found in Travis-CI, and leave behind a list of tasks to be done over there.
