### PR TITLE
Fix support for label selectors

### LINKED ISSUE #965: application.name field became mandatory/redundant in release 0.7.x
### What is the environment (Minikube, Openshift)?
OCP 4.6.16 on premises

### What is the SBO version used?
0.7.0
0.7.1

### What are the steps to reproduce this issue?
  1. Install the SBO operator (see attached `subscription.yaml` in attached archive)
  2. Deploy a sample app, using [these instructions](https://github.com/redhat-developer/service-binding-operator/tree/master/examples/nodejs_postgresql#import-an-application)
  3. Apply the binding request (see `binding-request-noname.yaml` in attached archive) , which uses label selectors to match the application:
      ```
      oc project service-binding-demo
      oc apply -f binding-request-noname.yaml
      ```
  4. Inspect logs for SBO pod (see `logs` in attached archive)
      ```
     {"level":"error","ts":1621375914.120951,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"binding.operators.coreos.com","reconcilerKind":"ServiceBinding","controller":"servicebinding","name":"binding-request-noname","namespace":"service-binding-demo","error":"name is required"
      ```
  5. Now "fix" the `ServiceBinding` by adding the redundant `name` field:
      ```
      oc apply -f binding-request-with-name.yaml
      ```
  6. Inspect logs for SBO pod (see `logs` in attached archive) and see a successful message:
      ```
    {"level":"info","ts":1621376188.5513623,
     "logger":"controllers.ServiceBinding",
     "msg":"Done","serviceBinding":"service-binding-demo/binding-request-name"
      ```

### What is the expected behaviour?
Service binding should be processed without issue and mapped to the matching application.

### What is the actual behaviour?
Operator logs surface an error in the binding request, indicating that the `.spec.application.name` must be filled out, even though `.spec.application.labelSelector` is specified.

### Service Binding Operator Logs
See `logs` in attached archive.

### Additional Information (Screenshots, etc)
This same `binding-request-noname.yaml` file worked correctly ysing the operator version 0.6.0.
I can see the secret created by the operator:

```
 oc get Secret binding-request-noname-6f93c924eb98fbd528c74b610b632229352734c1 -n service-binding-demo -o jsonpath={.data}
map[env.json:ew...==]
```

And I can see it mounted to the application
```
oc get pod nodejs-rest-http-crud-7dfd6855db-r5s5s -n service-binding-demo -o jsonpath="{.spec.containers[].volumeMounts}" 
[map[name:binding-request-noname mountPath:/config] ...
```

[Archive.zip](https://github.com/redhat-developer/service-binding-operator/files/6504896/Archive.zip)

### PR DESCRIPTION
**Pull request by baijum**
- Fix `.spec.application.name` field becoming mandatory
- If more than one application is selected through label selectors, all will be considered for binding

Fixes #965

- [x] acceptance test demonstrating how to bind 2 applications having the same label.
- [x] Remove `InvalidApplicationReference` reason and corresponding code and tests
  - [x] Added issue #974
- [x] Wrong assertion for the test: `should return an error if application list returns error`

### CODE REVIEW

File: pkg/reconcile/pipeline/context/impl.go [hunk 1]
```diff
@@ -118,15 +121,44 @@ func (i *impl) Services() ([]pipeline.Service, error) {
 func (i *impl) Applications() ([]pipeline.Application, error) {
 	if i.applications == nil {
 		if ref := i.serviceBinding.Spec.Application; ref != nil {
-			gvr, err := i.typeLookup.ResourceForReferable(ref)
-			if err != nil {
-				return nil, err
+			if i.serviceBinding.Spec.Application.Name != "" &&
+				i.serviceBinding.Spec.Application.LabelSelector != nil &&
+				i.serviceBinding.Spec.Application.LabelSelector.MatchLabels != nil {
+				return nil, errs.New("Both label selector and name for application should be used")
```
Comment (pedjak) [inline pkg/reconcile/pipeline/context/impl.go:127]: you mean - "should not be used"?

File: pkg/reconcile/pipeline/context/impl.go [hunk 2]
```diff
@@ -118,15 +121,44 @@ func (i *impl) Services() ([]pipeline.Service, error) {
...
+				}
+				u, err := i.client.Resource(*gvr).Namespace(i.serviceBinding.Namespace).Get(context.Background(), ref.Name, metav1.GetOptions{})
+				if err != nil {
+					return nil, err
+				}
+				i.applications = append(i.applications, &application{gvr: gvr, persistedResource: u, bindingPath: i.serviceBinding.Spec.Application.BindingPath})
+
+			}
+			if i.serviceBinding.Spec.Application.LabelSelector != nil && i.serviceBinding.Spec.Application.LabelSelector.MatchLabels != nil {
+				gvr, err := i.typeLookup.ResourceForReferable(ref)
```
Comment (pedjak) [inline pkg/reconcile/pipeline/context/impl.go:142]: this lines repeats also in line 130 - so it could be moved before back to the original place.

File: pkg/reconcile/pipeline/context/impl.go [hunk 3]
```diff
@@ -118,15 +121,44 @@ func (i *impl) Services() ([]pipeline.Service, error) {
...
+					LabelSelector: labels.Set(matchLabels).String(),
+				}
+
+				objList, err := i.client.Resource(*gvr).Namespace(i.serviceBinding.Namespace).List(context.Background(), opts)
+				if err != nil {
+					return nil, err
+				}
+
+				if len(objList.Items) == 0 {
+					return nil, errs.New("application not found")
```
Comment (pedjak) [inline pkg/reconcile/pipeline/context/impl.go:154]: the contract of this method is to return empty array, not array if not applications are not found, see the doc: https://github.com/redhat-developer/service-binding-operator/blob/d680987ea0f2869557ada3f3dcc621981cb1d427/pkg/reconcile/pipeline/api.go#L102

File: pkg/reconcile/pipeline/context/impl_test.go [hunk 4]
```diff
@@ -91,6 +92,51 @@ var _ = Describe("Context", func() {
 			Entry("no binding path specified", nil, defaultContainerPath),
 			Entry("binding path specified", &v1alpha1.BindingPath{ContainersPath: "foo.bar"}, "foo.bar"),
 		)
+		DescribeTable("should return slice of size 1 if application is specifiedt through label seclector", func(bindingPath *v1alpha1.BindingPath, expectedContainerPath string) {
```
Comment (pedjak) [inline pkg/reconcile/pipeline/context/impl_test.go:95]: typo "specifiedt"

Comment (pedjak) [reply pkg/reconcile/pipeline/context/impl_test.go:95]: it would be also more interesting to cover the case when there at least two applications with the same label - with that we check if the loop in https://github.com/redhat-developer/service-binding-operator/pull/971/files#diff-0168dc7ac8aa540873af78cf38f886f6a5ace89fb75dce9880490cedbed1d46eR157 really works.

**Review by pedjak — CHANGES_REQUESTED** [review]
a few more unit tests are missing:

* when both application name and selector are set
* when label selector is used but no application is annotated so the result is empty
* there is an error at performing `List` call

and acceptance tests demonstrating the usage of the label selector and the situation when both name and label selector are set.

File: pkg/reconcile/pipeline/context/impl.go (hunk 3 above)
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl.go:154]: Returning `nil` returns an empty slice of `Application` objects.
See this example: https://play.golang.org/p/QvQLT9CH3Fg

File: pkg/reconcile/pipeline/context/impl.go (hunk 2 above)
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl.go]: Done. 5326c6f674cb869fdaa8242bd4cc454fb72941cc

File: pkg/reconcile/pipeline/context/impl.go (hunk 1 above)
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl.go]: Done. 5326c6f674cb869fdaa8242bd4cc454fb72941cc

File: pkg/reconcile/pipeline/context/impl_test.go (hunk 4 above)
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl_test.go]: Done. 5326c6f674cb869fdaa8242bd4cc454fb72941cc

File: pkg/reconcile/pipeline/context/impl.go (hunk 3 above)
Comment (pedjak) [reply pkg/reconcile/pipeline/context/impl.go:153]: Thanks, nice. However, according to the contract, we should not return  error in this place, just empty slice.

Comment (baijum) [reply pkg/reconcile/pipeline/context/impl.go]: Fixed and added a test case for the same: 588535ccd6305f26c5dfe8e2ac33909a1d313ad9

**Comment by pedjak** [comment]
@baijum can you think about some better commit message/PR summary describing what was done and how?

**Comment by isutton** [comment]
> @baijum commented on this pull request.
> Returning `nil` returns an empty slice of `Application` objects.
> See this example: https://play.golang.org/p/QvQLT9CH3Fg

In this particular case, 'nil' is an un-initialized slice of a
Application items, not an empty initialized slice of Application
items.

***@***.***/golang-nil-vs-empty-slice-87fd51c0a4d
I've found a good summary on why this matters.

**Comment by baijum** [comment]
> @baijum can you think about some better commit message/PR summary describing what was done and how?

**Comment by baijum** [comment]
> In this particular case, 'nil' is an un-initialized slice of a Application items, not an empty initialized slice of Application items. 

Done. 538772c41782fe9cff89843112f7227d5433e51b

**Comment by baijum** [comment]
> and acceptance tests demonstrating the usage of the label selector and the situation when both name and label selector are set.

I missed this. I will work on this.

**Comment by baijum** [comment]
> > and acceptance tests demonstrating the usage of the label selector and the situation when both name and label selector are set.
> 
> I missed this. I will work on this.

Done. 5e472beddfcb48376f4bcd3620282d8ec3437082

**Comment by baijum** [comment]
> * when both application name and selector are set

Done. 7debb128ae498a821dd404ba57825f8deeddffe5

**Comment by baijum** [comment]
> * there is an error at performing `List` call

I couldn't figure out how to produce an error in the `List` call. Let me if we can skip this for now.

File: test/acceptance/features/bindAppToServiceWithLabelSelector.feature [hunk 5]
```diff
@@ -0,0 +1,111 @@
+Feature: Bind an application with label selector to a service
```
Comment (pedjak) [inline test/acceptance/features/bindAppToServiceWithLabelSelector.feature:1]: should we really consider this as a separate feature? this is all about referring application resources using attached labels

File: test/acceptance/features/bindAppToServiceWithLabelSelector.feature [hunk 6]
```diff
@@ -0,0 +1,111 @@
...
+
+    As a user of Service Binding Operator
+    I want to bind applications with label selector to services it depends on
+
+    Background:
+        Given Namespace [TEST_NAMESPACE] is used
+        * Service Binding Operator is running
+
+    Scenario: Bind an application with label selector to backend service
```
Comment (pedjak) [inline test/acceptance/features/bindAppToServiceWithLabelSelector.feature:10]: application resource has labels attached, but label selector is used inside service binding to define what application should be bound. Could we be a bit more verbose about the setup and the expected outcome? For example:

```
Bind successfully an application owning a given label to a service
```

File: test/acceptance/features/bindAppToServiceWithLabelSelector.feature [hunk 7]
```diff
@@ -0,0 +1,111 @@
...
+                        app: gen-app-a-s-c
+                    group: apps
+                    version: v1
+                    resource: deployments
+            """
+        Then Service Binding "service-binding-a-s-c" is ready
+        And The application env var "BACKEND_USERNAME" has value "AzureDiamond"
+        And The application env var "BACKEND_PASSWORD" has value "hunter2"
+
+    Scenario: Attempt to bind an application with label selector and name to a service
```
Comment (pedjak) [inline test/acceptance/features/bindAppToServiceWithLabelSelector.feature:60]: please rephrase to include the outcome as well.. in this case service binding will be unsuccessful, right?

File: test/acceptance/features/bindAppToServiceWithLabelSelector.feature [hunk 8]
```diff
@@ -0,0 +1,111 @@
...
+                      matchLabels:
+                        app: gen-app-a-s-e
+                    group: apps
+                    version: v1
+                    resource: deployments
+            """
+
+        Then jq ".status.conditions[] | select(.type=="CollectionReady").status" of Service Binding "service-binding-a-s-e" should be changed to "True"
+        And jq ".status.conditions[] | select(.type=="InjectionReady").status" of Service Binding "service-binding-a-s-e" should be changed to "False"
+        And jq ".status.conditions[] | select(.type=="InjectionReady").reason" of Service Binding "service-binding-a-s-e" should be changed to "ApplicationNotFound"
```
Comment (pedjak) [inline test/acceptance/features/bindAppToServiceWithLabelSelector.feature:110]: IMHO - `ApplicationNotFound` is not correct reason - simply we do not allow name and label to cooexist - Hence, something like `InvalidApplicationReference` should be more appropriate.

**Review by pedjak — CHANGES_REQUESTED** [review]
it would be good to have an additonal acceptance test demonstrating how to bind 2 applications having the same label.

**Comment by pedjak** [comment]
> I couldn't figure out how to produce an error in the List call. Let me know if we can skip this for now.

@baijum use `PrependReactor` on the fake client and define for what verb and resource you would like to have an error. Something like: https://github.com/kubernetes/client-go/issues/742#issuecomment-633676780

**Comment by baijum** [comment]
> > I couldn't figure out how to produce an error in the List call. Let me know if we can skip this for now.
> 
> @baijum use `PrependReactor` on the fake client and define for what verb and resource you would like to have an error. Something like: [kubernetes/client-go#742 (comment)](https://github.com/kubernetes/client-go/issues/742#issuecomment-633676780)

Done. ee27a52e503e89daa95b50a3f4549960af35dcee

**Comment by pmacik** [comment]
@baijum FYI, PR checks fails because of an issue with the workflows. This PR https://github.com/redhat-developer/service-binding-operator/pull/973 fixes that.

File: pkg/reconcile/pipeline/context/impl.go [hunk 9]
```diff
@@ -118,15 +121,44 @@ func (i *impl) Services() ([]pipeline.Service, error) {
...
+				i.serviceBinding.Spec.Application.LabelSelector != nil &&
+				i.serviceBinding.Spec.Application.LabelSelector.MatchLabels != nil {
+				return nil, errs.New("Both label selector and name for application should not be used")
+			}
 			gvr, err := i.typeLookup.ResourceForReferable(ref)
-			if err != nil {
-				return nil, err
+			if i.serviceBinding.Spec.Application.Name != "" {
+				if err != nil {
+					return nil, err
```
[the remark this answers is not in the document]
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl.go]: Done. af6e990baa021c05e9fba2e7cb713ac745500ba9

File: pkg/reconcile/pipeline/context/impl.go [hunk 10]
```diff
@@ -118,15 +121,44 @@ func (i *impl) Services() ([]pipeline.Service, error) {
...
+				}
+
+				objList, err := i.client.Resource(*gvr).Namespace(i.serviceBinding.Namespace).List(context.Background(), opts)
+				if err != nil {
+					emptyResult := make([]pipeline.Application, 0)
+					return emptyResult, err
+				}
+
+				if len(objList.Items) == 0 {
+					return nil, nil
```
[the remark this answers is not in the document]
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl.go]: Done. af6e990baa021c05e9fba2e7cb713ac745500ba9

File: pkg/reconcile/pipeline/context/impl_test.go [hunk 11]
```diff
@@ -91,7 +92,175 @@ var _ = Describe("Context", func() {
 			Entry("no binding path specified", nil, defaultContainerPath),
 			Entry("binding path specified", &v1alpha1.BindingPath{ContainersPath: "foo.bar"}, "foo.bar"),
 		)
+		DescribeTable("should return slice of size 1 if application is specified through label seclector", func(bindingPath *v1alpha1.BindingPath, expectedContainerPath string) {
```
[the remark this answers is not in the document]
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl_test.go]: Done. af6e990baa021c05e9fba2e7cb713ac745500ba9

File: pkg/reconcile/pipeline/context/impl_test.go [hunk 12]
```diff
@@ -91,7 +92,175 @@ var _ = Describe("Context", func() {
...
+			u2.SetGroupVersionKind(schema.GroupVersionKind{Group: "app", Version: "v1", Kind: "Foo"})
+			u2.SetLabels(map[string]string{"env": "prod"})
+
+			client := fake.NewSimpleDynamicClient(runtime.NewScheme(), u1, u2)
+
+			ctx := &impl{client: client, serviceBinding: &sb, typeLookup: typeLookup}
+
+			applications, err := ctx.Applications()
+			Expect(err).NotTo(HaveOccurred())
+			Expect(applications).To(HaveLen(2))
```
[the remark this answers is not in the document]
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl_test.go]: Done. af6e990baa021c05e9fba2e7cb713ac745500ba9

File: pkg/reconcile/pipeline/context/impl_test.go [hunk 13]
```diff
@@ -91,7 +92,175 @@ var _ = Describe("Context", func() {
...
+
+			ref := v1alpha1.Application{
+				Ref: v1alpha1.Ref{
+					Group:   "app",
+					Version: "v1",
+					Kind:    "Foo",
+					Name:    "app1",
+				},
+				LabelSelector: ls,
+			}
```
[the remark this answers is not in the document]
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl_test.go]: The test is to check the effect of two kinds of application references: label & name.
Even though it is not directly used, this setup is required to validate the functionality.

File: pkg/reconcile/pipeline/context/impl_test.go [hunk 14]
```diff
@@ -91,7 +92,175 @@ var _ = Describe("Context", func() {
...
+
+			sb := v1alpha1.ServiceBinding{
+				ObjectMeta: metav1.ObjectMeta{
+					Name:      "sb1",
+					Namespace: "ns1",
+				},
+				Spec: v1alpha1.ServiceBindingSpec{
+					Application: &ref,
+				},
+			}
```
[the remark this answers is not in the document]
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl_test.go:255]: The test is to check the effect of two kinds of application references: label & name.
Even though it is not directly used, this setup is required to validate the functionality.

File: pkg/reconcile/pipeline/context/impl_test.go [hunk 15]
```diff
@@ -91,7 +92,175 @@ var _ = Describe("Context", func() {
...
+			client := fake.NewSimpleDynamicClient(runtime.NewScheme())
+
+			ctx := &impl{client: client, serviceBinding: &sb, typeLookup: typeLookup}
+
+			_, err := ctx.Applications()
+			Expect(err).To(HaveOccurred())
```
[the remark this answers is not in the document]
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl_test.go:269]: Done. af6e990baa021c05e9fba2e7cb713ac745500ba9

File: test/acceptance/features/bindAppToServiceWithLabelSelector.feature (hunk 6 above)
Comment (baijum) [reply test/acceptance/features/bindAppToServiceWithLabelSelector.feature]: Done. af6e990baa021c05e9fba2e7cb713ac745500ba9

File: test/acceptance/features/bindAppToServiceWithLabelSelector.feature (hunk 7 above)
Comment (baijum) [reply test/acceptance/features/bindAppToServiceWithLabelSelector.feature]: Done. af6e990baa021c05e9fba2e7cb713ac745500ba9

**Comment by baijum** [comment]
> it would be good to have an additonal acceptance test demonstrating how to bind 2 applications having the same label.

I will work on this.

File: test/acceptance/features/bindAppToServiceWithLabelSelector.feature (hunk 8 above)
Comment (baijum) [reply test/acceptance/features/bindAppToServiceWithLabelSelector.feature:110]: I need some more time to figure out how to introduce a new failure reason.

File: test/acceptance/features/bindAppToServiceWithLabelSelector.feature (hunk 5 above)
Comment (baijum) [reply test/acceptance/features/bindAppToServiceWithLabelSelector.feature:1]: I think a separate feature file for the label selector is fine.

File: pkg/reconcile/pipeline/context/impl.go [hunk 16]
```diff
@@ -118,15 +121,43 @@ func (i *impl) Services() ([]pipeline.Service, error) {
...
+				if err != nil {
+					return emptyResult, err
+				}
+
+				if len(objList.Items) == 0 {
+					return emptyResult, nil
+				}
+
+				for index, _ := range objList.Items {
+					i.applications = append(i.applications, &application{gvr: gvr, persistedResource: &(objList.Items[index]), bindingPath: i.serviceBinding.Spec.Application.BindingPath})
```
Comment (baijum) [inline pkg/reconcile/pipeline/context/impl.go:157]: The `persistedResource` value (address of the item) is taken using the index.
Ref. https://play.golang.org/p/ePs7st6f91g

File: test/acceptance/features/bindAppToServiceWithLabelSelector.feature (hunk 5 above)
Comment (pedjak) [reply test/acceptance/features/bindAppToServiceWithLabelSelector.feature:1]: can you backup your statement with some reason?

Comment (baijum) [reply test/acceptance/features/bindAppToServiceWithLabelSelector.feature:1]: I am fine with moving to another file. Please suggest the file.

File: pkg/reconcile/pipeline/context/impl.go [hunk 17]
```diff
@@ -118,15 +121,43 @@ func (i *impl) Services() ([]pipeline.Service, error) {
 func (i *impl) Applications() ([]pipeline.Application, error) {
 	if i.applications == nil {
 		if ref := i.serviceBinding.Spec.Application; ref != nil {
+			if i.serviceBinding.Spec.Application.Name != "" &&
+				i.serviceBinding.Spec.Application.LabelSelector != nil &&
+				i.serviceBinding.Spec.Application.LabelSelector.MatchLabels != nil {
+				return nil, errs.New("Both label selector and name for application should not be used")
```
Comment (pedjak) [inline pkg/reconcile/pipeline/context/impl.go:127]: we can extract error into a var that can be used later in test assertion - instead of string copying.

File: pkg/reconcile/pipeline/context/impl_test.go [hunk 18]
```diff
@@ -91,7 +94,182 @@ var _ = Describe("Context", func() {
...
+				Spec: v1alpha1.ServiceBindingSpec{
+					Application: &ref,
+				},
+			}
+
+			u := &unstructured.Unstructured{}
+			u.SetName("app")
+			u.SetNamespace(sb.Namespace)
+			u.SetGroupVersionKind(schema.GroupVersionKind{Group: "app", Version: "v1", Kind: "Foo"})
+			u.SetLabels(map[string]string{"env": "stage"})
```
Comment (pedjak) [inline pkg/reconcile/pipeline/context/impl_test.go:223]: we do not need to create any app object at all, since we are going to fail earlier. Omitting this will also implicitly check that we do not try to access the cluster for this scenario.

File: pkg/reconcile/pipeline/context/impl_test.go [hunk 19]
```diff
@@ -91,7 +94,182 @@ var _ = Describe("Context", func() {
...
+				func(action testing.Action) (handled bool, ret runtime.Object, err error) {
+					return true, &v1.DeploymentList{}, e.New("Error listing foo")
+				})
+
+			ctx := &impl{client: client, serviceBinding: &sb, typeLookup: typeLookup}
+
+			_, err := ctx.Applications()
+			Expect(err).To(HaveOccurred())
+			// FIXME: This is not the expected error message
+			Expect(err.Error()).To(ContainSubstring("no kind is registered for the type v1.DeploymentList in scheme"))
```
Comment (pedjak) [inline pkg/reconcile/pipeline/context/impl_test.go:271]: the error should be the same as the one you put in line 263: "Error listing foo"

**Review by pedjak — CHANGES_REQUESTED** [review]

File: pkg/reconcile/pipeline/context/impl_test.go (hunk 19 above)
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl_test.go:271]: For some reason, that error message is not coming. I have used `client.PrependReactor` (line 261-264) as per earlier suggestion, so the listing failed as expected.
I tried to use `unstructured.Unstructured{}` instead of `v1.DeploymentList{}`, but that also seems to be not working. I will come back to this issue once everything else finished.

File: pkg/reconcile/pipeline/context/impl_test.go [hunk 20]
```diff
@@ -91,7 +94,182 @@ var _ = Describe("Context", func() {
...
+
+			ctx := &impl{client: client, serviceBinding: &sb, typeLookup: typeLookup}
+
+			applications, err := ctx.Applications()
+			Expect(err).NotTo(HaveOccurred())
+			Expect(applications).To(HaveLen(2))
+			Expect(applications[0].Resource()).To(Equal(u1))
+			Expect(applications[0].ContainersPath()).To(Equal(expectedContainerPath))
+			Expect(applications[1].Resource()).To(Equal(u2))
+			Expect(applications[1].ContainersPath()).To(Equal(expectedContainerPath))
```
[the remark this answers is not in the document]
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl_test.go:146]: Order is not reliable and not part of the API.

[the remark this answers is not in the document]
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl_test.go:146]: Check Omega assertion library.

**Comment by baijum** [comment]
> > it would be good to have an additonal acceptance test demonstrating how to bind 2 applications having the same label.
> 
> I will work on this.

Done. 53bb65a118d53a3a3e299860f4b3473f88d2b42d

File: pkg/reconcile/pipeline/context/impl.go (hunk 17 above)
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl.go]: Created separate issue: #974

File: pkg/reconcile/pipeline/context/impl_test.go (hunk 18 above)
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl_test.go]: This code has been removed. Ref.  #974

File: pkg/reconcile/pipeline/context/impl_test.go (hunk 19 above)
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl_test.go]: Done. 82294850ad30c8fea6de5e767b5852a5d0158c51

File: pkg/reconcile/pipeline/context/impl_test.go (hunk 20 above)
[the remark this answers is not in the document]
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl_test.go]: Done. b46fe696d76e4318cfa1d8871a25b2d0c32a902a

File: pkg/reconcile/pipeline/context/impl_test.go [hunk 21]
```diff
@@ -91,7 +93,145 @@ var _ = Describe("Context", func() {
...
+				},
+			}
+
+			gvr := &schema.GroupVersionResource{Group: "app", Version: "v1", Resource: "foos"}
+			typeLookup.EXPECT().ResourceForReferable(&ref).Return(gvr, nil)
+
+			client := fake.NewSimpleDynamicClient(runtime.NewScheme())
+			client.PrependReactor("list", "foos",
+				func(action testing.Action) (handled bool, ret runtime.Object, err error) {
+					return true, nil, e.New("Error listing foo")
```
Comment (pedjak) [inline pkg/reconcile/pipeline/context/impl_test.go:226]: DRY: please extract error in a variable and use it later in the assertion

File: pkg/reconcile/pipeline/context/impl_test.go [hunk 22]
```diff
@@ -91,7 +93,145 @@ var _ = Describe("Context", func() {
...
+				})
+
+			ctx := &impl{client: client, serviceBinding: &sb, typeLookup: typeLookup}
+
+			_, err := ctx.Applications()
+			Expect(err).To(HaveOccurred())
+			Expect(err.Error()).To(ContainSubstring("Error listing foo"))
```
Comment (pedjak) [inline pkg/reconcile/pipeline/context/impl_test.go:233]: The error we get must be the one we got from the client, and the message should be the identical. Such assertion assures that the error is propagated to the caller:

```
Expect(err).To(Equal(expectedError))
```

File: pkg/reconcile/pipeline/context/impl_test.go [hunk 23]
```diff
@@ -122,6 +262,7 @@ var _ = Describe("Context", func() {
 			Expect(err).To(HaveOccurred())
 			Expect(errors.IsNotFound(err)).To(BeTrue())
 		})
+
```
Comment (pedjak) [inline pkg/reconcile/pipeline/context/impl_test.go:265]: please revert unrelated whitespace change.

File: test/acceptance/features/steps/generic_testapp.py [hunk 24]
```diff
@@ -74,3 +76,33 @@ def check_file_value(context, file_path):
...
+@given(u'The common label "{label}" is set for both apps')
+def set_common_label(context, label):
+    context.application1.set_label(f"{label}")
+    context.application2.set_label(f"{label}")
+
+
+@then(u'The application env var "{name}" has value "{value}" in both apps')
+def check_env_var_value_in_both_apps(context, name, value):
+    found = polling2.poll(lambda: context.application1.get_env_var_value(name) == value, step=5, timeout=400)
+    assert found, f'Env var "{name}" should contain value "{value}" in {context.application1}'
```
Comment (pedjak) [inline test/acceptance/features/steps/generic_testapp.py:105]: if we reach this line, then `found` is `true` always - otherwise Timeout exception occurs. Hence, this and the similar line at line 108 can be removed.

**Review by pedjak — CHANGES_REQUESTED** [review]

File: test/acceptance/features/steps/generic_testapp.py (hunk 24 above)
Comment (baijum) [reply test/acceptance/features/steps/generic_testapp.py]: Done. 5e91f6d96db0011740c9422b96e2de2d0a654551

File: pkg/reconcile/pipeline/context/impl_test.go (hunk 23 above)
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl_test.go]: Done. 5e91f6d96db0011740c9422b96e2de2d0a654551

File: pkg/reconcile/pipeline/context/impl_test.go (hunk 22 above)
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl_test.go]: Done. 5e91f6d96db0011740c9422b96e2de2d0a654551

File: pkg/reconcile/pipeline/context/impl_test.go (hunk 21 above)
Comment (baijum) [reply pkg/reconcile/pipeline/context/impl_test.go]: Done. 5e91f6d96db0011740c9422b96e2de2d0a654551

**Review by pedjak — APPROVED** [review]
+1 after having required CI jobs passing. Please also squash the commits.
